### ISSUE TITLE
Allow broadcaster to be set using name of broadcaster in subscribe options

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper#102]
Currently the broadcaster can be specified as `broadcaster: XXX` or `async: true`.

When there are more than just sync and async broadcasters in a project it would be useful to use the broadcasters key to set it.

For example if both wisper-celluloid and wisper-sidekiq in Gemfile then both will set the `async` broadcaster, in this case instead of doing `broadcaster: :celluloid` we can do `celluloid: true`.

``` ruby
subscribe(listener, celluloid: true)
```

**Comment by antulik** [comment]
what are the benefits for that? and what will happend when there are multiple broadcasters `subscribe(listener, celluloid: true, sidekiq: true)` ?

**Comment by krisleech** [comment]
For me, it just looks, visually, more appealing to put `celluloid: true`, instead of `broadcaster: 'celluloid'`. 

I think multiple would need to raise.

**Comment by antulik** [comment]
personally I would stick with the current approach as it has less ambiguity and less space for errors. Maybe just rename `broadcaster` to something more english like, e.g. `through`

```
subscribe(listener, through: :celluloid)
```
