### ISSUE TITLE
One of my broadcast calls does not work in production

### ISSUE THREAD

**Issue by mbajur** [krisleech/wisper#107]
Hi,
i have a really ridiculous situation going on my production server. I'm using wisper with my rails app and, from among about 50 `broadcast` calls here and there in my source code, one of these `broadcast` calls is not beeing triggered. 

I'm defining a global listeners in rails initializers:

```
# config/initializers/wisper.rb
Wisper.subscribe(LogListener.new)
# ... other listeners
```

And LogListener looks like that:

```
class LogListener

  def create_job_success(job)
    log "Job has been created [##{job.id}]"
  end

  def create_job_success2(job)
    log "Job has been created [##{job.id}]"
  end

  def test_event
    log "It works"
  end
end
```

And also i have a service which, let's say, have a following code:

```
class MyService
  def call
    broadcast :test_event
    broadcast :create_job_success
    broadcast :create_job_success2
    broadcast :test_event
  end
end
```

And here is the deal - when running my service with `MyService.new.call`, i will always get 'It works' produced by `test_event` broadcast and `create_job_success2` is also beeing triggered (i have that fully covered by rspec tests). What's more - according to rspec results, `create_job_success` is also getting triggered properly (these specs covers only this single `MyService` class, nothing more. So the issue can be somewhere else) .

However, in production, this `create_job_success` event is not getting triggered (while the others are getting triggered properly - i know that by watching log results produced by LogListener). I also can't see any exception or antyhing like that - it just doesn't work and falls silently.

That situation drives me mad becuase i'm completely not able to debug what's going on and my boss want's to kill me so i have a question to you guys - have you any idea what can possibly create such situation, in which wisper loggers/listeners fails silently or have you any idea what can be wrong with my code?

Thanks in advance!

**Comment by mbajur** [comment]
Ok i have  just resolved that issue by myself. It was caused by the fact, that, apart of global listeners, i was using a object listener which was returning nil (what actually should it return?)

```
service = MyService.new

service.on(:create_job_success) do
  # something
  return
end

service.call
```

And that was pausing all the other [global] listeners. I hope it would be helpfull for someone in the future.

**Comment by krisleech** [comment]
Glad you figured it out, there was a recent blog post about this gotcha. I should add a note to the README about not returning in blocks.

http://product.reverb.com/2015/02/28/the-strange-case-of-wisper-and-ruby-blocks-behaving-like-procs/
