### ISSUE TITLE
Publish for class method

### ISSUE THREAD

**Issue by micheldoumit** [krisleech/wisper#113]
When I try to publish something from a class method it returns the error:

```undefined method `publish' for Fo:Class```

```ruby
class Foo
   include Wisper::Publisher

   def self.do_something
      publish(:something_happened)
   end
end
```

What would be the suggested approach here ?

**Comment by krisleech** [comment]
You can only publish from instances, not classes. You could try this:

```ruby
class Foo
  include Wisper::Publisher

  def self.do_something
    new.do_something
  end

  def do_something
    publish(:soemthing_happened)
  end
end
```

**Comment by krisleech** [comment]
One other thing you could try is `extend Wisper::Publisher`, this might work.

**Comment by micheldoumit** [comment]
Thanks :-)

**Comment by pecavalheiro** [comment]
Hi, I'm facing the same issue as explained. Could you please clarify the reason why Wisper was designed to allow only publishing/broadcasting only from instances and not from classes?

I have a situation where I need to broadcast messages from static classes. I'm considering writing a wrapper class to allow `.new.broadcast`, but to be honest I don't see why this is not supported natively. 

Thank you!
