### ISSUE TITLE
Accidently used `subscribe` instead of `on` to subscribe a block

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper#114]
```ruby
class Foo; include Wisper.publisher; end

f = Foo.new
f.subscribe(:success) { ... }
f.send(:broadcast, :success)
```

In the above example I want to subscribe a block, for which I should use `on`. I accidently used `subscribe` but I got no error despite the [method signature](https://github.com/krisleech/wisper/blob/master/lib/wisper/publisher.rb#L13) not allowing for a block...

**Comment by evanboho** [comment]
In Ruby, you can pass a block to a method regardless of whether `&block` is in the args list. In fact, it's [faster](http://mudge.name/2011/01/26/passing-blocks-in-ruby-without-block.html) to not pass it—or at least it used to be in 1.9.

**Comment by krisleech** [comment]
@evanboho Ah, of course, `yield`. That explains the problem. I might be able to use `block_given?` to test for a block and raise a helpful error.
