### ISSUE TITLE
Testing Wisper with Minitest

### ISSUE THREAD

**Issue by olance** [krisleech/wisper#115]
Hi,

this is not really an issue... just wanted to let you know that I've began porting wisper-rspec to a [wisper-minitest](https://github.com/digitalcuisine/wisper-minitest) gem!

Hopefully it'll be useful for people who want to use Minitest as their testing framework.

**Comment by krisleech** [comment]
Excellent! We can change [this section](https://github.com/krisleech/wisper#rspec) of the README to be "Testing" and link to both the minitest and rspec gems. 

Please let me know when you release the first version.

**Comment by olance** [comment]
:)
I already have released a 0.0.1 version which is very minimal (only provides `assert_broadcast`).
I'll let you know when it's a bit more advanced!

**Comment by krisleech** [comment]
How you getting on, any news? :smile:

**Comment by olance** [comment]
hey!

sorry my time's been sucked up by other things, I'll try to finish the gem soon and I'll let you know :)

**Comment by krisleech** [comment]
no problems, thanks :+1:
