### ISSUE TITLE
Temporary Listener for all events

### ISSUE THREAD

**Issue by Canifex** [krisleech/wisper#117]
Is there any possibility to listen to all events without explicitly defining them? So to say, to define a "wrapper" or a "proxy" method which is called if any event is emitted, but without a) defining a method for each event and b) loosing the information about the fired event?

I know I can use the "with" method to redirect all events to one method, but this way I gonna loose the (very important) information, which event was called originally. The other option I can think of (if overwriting "send" in my listener is not an option...) is writing my own broadcaster (like this https://github.com/krisleech/wisper/blob/master/lib/wisper/broadcasters/logger_broadcaster.rb) for it, but can I attach this broadcaster only for one temporary subscription like this:

```ruby
Wisper.subscribe(MyPublicLoggingListener.new, broadcaster: :my_logging_broadcaster) do 
  # anything
end

class MyPublicLoggingListener
  def any_event_emitted(event)
    log(event)
  end
end
```

**Comment by krisleech** [comment]
I can think of a couple of options of the top of my head.

You could use `method_missing`. 

```ruby
class MyListener
  def respond_to?(name)
    true
  end

  def method_missing(name, args, &block)
    # handle event...
  end
end
```

Or, you could, as you suggest, write a custom broadcaster which calls a method such as `event_received` and passes the event name as well as the arguments, something like:

```ruby
class MySpecialBroadcaster
  def broadcast(listener, publisher, event, args)
    if listener.respond_to?(:event_received)
      listener.event_received(args.unshift(event))
    else
      raise ...
    end
  end
end

publisher.subscribe(listener, broadcaster: MySpecialBroadcaster.new)
```

You could even wrap the normal broadcaster as the LoggerBroadcaster does and get the above behaviour for all listeners:

```ruby
class MySpecialBroadcaster
  def initialize(broadcaster)
    @broadcaster = broadcaster
  end

  def broadcast(listener, publisher, event, args)
    listener.event_received(args.unshift(event)) if listener.respond_to?(:event_received)
    @broadcaster.broadcast(*args)
  end
end

Wisper.configure do |config|
  config.broadcaster :default, MySpecialBroadcaster.new(SendBroadcaster.new)
end
```

What do you think?

**Comment by Canifex** [comment]
I'm afraid touching only broadcasters won't work, since ObjectRegistration only calls the broadcaster if the listener has the specific method defined (https://github.com/krisleech/wisper/blob/master/lib/wisper/registration/object.rb#L17). And if I catch all events with the "with" option, the broadcaster does not get the information about the original event, instead the name of the method passed in "with" is given to him. I did not test it out, but this is my current understanding of the wisper codebase.

My current solution is to monkeypatch ObjectRegistration:
```ruby
# Monkeypatch: Adds event information if
# broadcasting via "with"
module Wisper
  class ObjectRegistration < Registration
    def broadcast(event, publisher, *args)
      method_to_call = map_event_to_method(event)
      if should_broadcast?(event) && listener.respond_to?(method_to_call) && publisher_in_scope?(publisher)
        if with
          broadcaster.broadcast(listener, publisher, method_to_call, args.unshift(event.to_sym))
        else
          broadcaster.broadcast(listener, publisher, method_to_call, args)
        end
      end
    end
  end
end
```

That way, listeners configured with the "with" option always get the event name as their first parameter. This works pretty good but requires the user to take at least this event parameter in his "with" configured method.

**Comment by krisleech** [comment]
The "method_missing" example should work, I use the same technique here: https://github.com/krisleech/wisper-rspec/blob/master/lib/wisper/rspec/matchers.rb#L5

You might be right about second "broadcaster" example, since the listener will not have a method handler for the event it will not call the broadcaster.

I did consider adding a feature which looks for an `on_event` method and calls it, this would happen in `ObjectRegistration`. This would be in addition to the usual behaviour of calling a method if it exists.

**Comment by krisleech** [comment]
@Canifex please re-open if you need more help. Thanks.
