### ISSUE TITLE
A copy of XXX has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by blanchma** [krisleech/wisper#119]
I'm getting this error very frequently:

A copy of EventDispatcher has been removed from the module tree but is still active!
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:479:in `load_missing_constant'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	/Users/Tute/playspace/game_events/app/listeners/event_dispatcher.rb:16:in `method_missing'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/wisper-celluloid-0.0.1/lib/wisper/celluloid_broadcaster.rb:17:in `public_send'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/wisper-celluloid-0.0.1/lib/wisper/celluloid_broadcaster.rb:17:in `broadcast'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/Tute/.rvm/gems/ruby-2.2.2@game-events/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

I'm using an async global listener, loaded in an initializer:
Wisper.subscribe(EventDispatcher.new, prefix: true, async: true)

**Comment by krisleech** [comment]
This is due to code rereloading in Rails development env, try this: https://stackoverflow.com/questions/28346609/reload-wisper-listeners-automatically-at-every-request/28362286#28362286

**Comment by blanchma** [comment]
Thanks, I will.

**Comment by krisleech** [comment]
success? :smile:

**Comment by blanchma** [comment]
@kris it success. Thanks! :)

2015-08-17 12:55 GMT-03:00 Kris Leech <notifications@github.com>:

**Comment by krisleech** [comment]
No problem, closing issue.

**Comment by ecbrodie** [comment]
I ran into this issue in my Rails project and I decided to use `before_initialize` instead of `to_prepare` so that I ensure that the clear runs only once during the initialization process for all environments.
