### ISSUE TITLE
A good way to test global listener

### ISSUE THREAD

**Issue by apraditya** [krisleech/wisper#123]
I have a global listener that updates some stats about the app. Something like this:

````
class MetricListener
  def article_is_published(_article, _author)
    metric.increment! :total_published_articles
  end

  private

  def metric
    @metric ||= Metric.last
  end
end
````

Each rspec file testing against these stats, have `FactoryGirl.create(:metric)` in the top `before` block. But due to `config.after do DatabaseCleaner.clean end` the test will always different Application metric. Is there a way to test global listener? I am using wisper version 1.x. Thanks

**Comment by krisleech** [comment]
I'd use regular RSpec such as:

```ruby
listener = MetricListener.new
expect { listener.article_is_published }.to change { Metric.last.total_published_articles }.by(1)
```

But I suspect I am missing something, can you provide more context about what you are trying to test. Can you post a more specific question and preferably the spec file you have.
