### ISSUE TITLE
[idea] Event Objects

### ISSUE THREAD

**Issue by antulik** [krisleech/wisper#124]
would be nice to be able to publish whole EventObject which would be converted to publish event and params.

The advantage of this you can provide a nice interface of params you are passing with custom functionality and don't worry about naming events.

Plus it will be easier to track if you miss-spelled class name, rather than string event name.

for example 

```ruby
class CreatedSuccess
  attr_accessor :message
  def initialise(message:)
    @message = message
  end
end

event = CreatedSuccess.new(message: 'hooray')
publisher.publish(event)

service.subscribe.on(CreatedSuccess) { |event|
  puts event.message
}
```

**Comment by krisleech** [comment]
I think this is a really good idea. I'm not sure how (or if) it could be incorporated in to Wisper because the `broadcast` and `subscribe` method signatures are different. Possibly it could be done in a separate gem which overrides `broadcast` and `subscribe` to parse the event object and call `super` with the correct signature.

Or it might be something we can incorporate in to Wisper 2.0.

**Comment by antulik** [comment]
tried to figure out my own solution, but got stuck with support of async, as sidekiq/activejob need to have args as hash but then that hash needs to be converted back to event object before method call. So I see that async gems will have to be changed as well to support that.

**Comment by krisleech** [comment]
If Event was simple like a Struct or Hash I think it could easily be serialized, I have a feeling Sidekiq/ActiveJob already do this. If not it wouldn't to be tricky to add.

**Comment by karmajunkie** [comment]
I'm actually doing this in my [replay](http://github.com/karmajunkie/replay) gem. Its been undergoing a major refactoring to replace its own event handling with Wisper and has some niceties for doing event-sourced projections, but as far as the event objects go, they're nice to have in a lot of ways. I'm using virtus for coerced-type attributes, and publishing events publishes the event class as the event name, the first parameter is the stream its being published on, and the second parameter is the event arguments. working out pretty well so far. Replay started as a bit of an experiment, but its been in use in production for almost two years now on a project and the newer version incorporates a lot of lessons learned from it.

**Comment by krisleech** [comment]
I'm going to close this for now. It will become a feature of Wisper 2.

**Comment by antulik** [comment]
@krisleech is this feature still on roadmap for wisper 2? (considering it's already rc1)

**Comment by krisleech** [comment]
It will be possible in Wisper 2.0, but I haven't had time to work on it for quite a while. It hasn't been a priority since it is mainly a rewrite.
