### ISSUE TITLE
Understanding Wisper's usage

### ISSUE THREAD

**Issue by synth** [krisleech/wisper#127]
The [Wisper gem][1] seems like a great approach to managing Pubsub functionality in a ruby(rails) app. I'm trying to understand its usage patterns though. The way publishing works, is great, but I'm confused why the majority of the documentation focuses on the pattern of subscribing to individual instances at runtime.

Consider: 

```ruby
    class Company
      include Wisper::Publisher

      after_create do 
        publish(:company_created, self)
      end
    end

    class SlackService
      include SlackNotifier
      def company_created(company)
        slack_says("Company was created on #{company.created_at}"
      end
    end
```

Then somewhere else(probably a controller), Wisper says to do something like this:

```ruby
    company = Company.new(params[:company])
    company.subscribe(SlackService)
    company.create
```

In this case, SlackService needs to know that an event it is interested in will be published in the create method, thereby coupling the two objects. If for whatever reason, the implementation changed so the event was published in the initialize method, the subscriber would be out of luck. The problem is minimized if you're dealing with simple service objects that just have a call or execute method, but still feels a bit awkward and potentially error prone.

Also, You are then prevented from using idioms like: ````Company.create(params[:company])````.

Also, what if companies are created in several sections of the app. I will then need to add subscribers all over the place. And even if you only create the company in one place, subscriptions in general will be scattered throughout the codebase.

I'm aware you can add Global handlers in an initializer which can be scoped to a class. This is probably the way to go for me(and imho, should be the main documented usage)

I like that Whisper is flexible enough to have a unique set of subscribers per individual instance, but I'm curious why this seems to be the main method of usage.

Are my thoughts about runtime, scattered subscription well founded or am I missing something about why Wisper was designed and documented primarily this way?

PS. I was thinking of posting this to SO, but I thought I'd try here first. Thanks.

  [1]: https://github.com/krisleech/wisper

**Comment by krisleech** [comment]
Would you mind putting this in StackOverflow please, that way it will always be visible and useful to future Googler's who have the same question. Feel free to post the link here and I will try and reply to some of the questions you have.
