### ISSUE TITLE
Passing an array to scope

### ISSUE THREAD

**Issue by mikeyhogarth** [krisleech/wisper#129]
The documentation doesnt' specify that this is possible, but I put a quick test together to see if it was possible to pass an array to the `scope` option. instead of this;

```
Wisper.subscribe(MySubscriber, async: true, scope: :ClassOne)
Wisper.subscribe(MySubscriber, async: true, scope: :ClassTwo)
```

We wanted to do this;
```
Wisper.subscribe(MySubscriber, async: true, scope: [:ClassOne, :ClassTwo])
```

If I put a PR together to add this in would you be open to merging it?

**Comment by krisleech** [comment]
Yes, I see we typecast to an `Array` [here](https://github.com/krisleech/wisper/blob/master/lib/wisper/registration/object.rb#L11). Please submit a PR to update the README and I will merge. Thanks :+1:

**Comment by krisleech** [comment]
I think you can also pass a `String` or `Class` too.

```
Wisper.subscribe(MySubscriber, async: true, scope: ClassOne)
Wisper.subscribe(MySubscriber, async: true, scope: [ClassOne, ClassTwo])
```
