### ISSUE TITLE
Spring wisper listener method caching

### ISSUE THREAD

**Issue by jmarceli** [krisleech/wisper#135]
It turns out that Spring caches my wisper listener method (I'm writing quite simple Engine).

Example:
**app/models/myengine/my_class.rb**
```
class Myengine::MyClass
  include Wisper::Publisher
  
  def something
    # some logic
    publish(:after_something, self)
  end
end
```
**config/initializers/wisper.rb**
```
Wisper.subscribe(Myengine::MyObserver.new)
```
**app/observers/myengine/my_observer.rb**
```
class Myengine::MyObserver
  def after_something my_class_instance
    # any changes here requires Spring manual restart in order to be reflected in tests
    another_method
  end

  def another_method
    # all changes here or in any other class methods works ok with Spring and are instantly visible in tests
    return true
  end
end
```

By Spring restart I mean manual execution of `spring stop` command which is really annoying.

What is more mysterious I may change `another_method` return value to false and then tests are failing which is OK, but when I change `after_something` method body to let say `return false` it doesn't have any effect on tests (like the body of the `after_something` is somehow cached).

It is not high priority problem because this strange behaviour is only visible inside listener method body and easy to overcome by moving all logic to another method in the class. Anyway it might be confusing (especially at the beginning when I didn't know the exact problem).

I made SO topic: http://stackoverflow.com/questions/36899306/rails-spring-custom-class-reloading because I was unsure if this is a Wisper issue.

**Comment by krisleech** [comment]
Thanks for creating the SO topic, much appreciated. I have responded there. If it fixes the problem please close this issue.

**Comment by jmarceli** [comment]
Many thanks for fast reply :)

For anyone interested please go to the: http://stackoverflow.com/questions/36899306/rails-spring-custom-class-reloading
