### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by kirantpatil** [krisleech/wisper#138]
Hi,

Is wisper Rails 5 compatible ?

Rails 5 has some modifications to callback methods as below and may be more.

For complete changelog: https://github.com/rails/rails/blob/fbdcf5221ad7ea3d40ad09651962fc85d101dd67/activerecord/CHANGELOG.md

Sean Griffin

Introduce after_{create,update,delete}_commit callbacks.

Before:

after_commit :add_to_index_later, on: :create
after_commit :update_in_index_later, on: :update
after_commit :remove_from_index_later, on: :destroy

After:

after_create_commit  :add_to_index_later
after_update_commit  :update_in_index_later
after_destroy_commit :remove_from_index_later

Fixes #22515.

**Comment by krisleech** [comment]
> Is wisper Rails 5 compatible ?

There is nothing Rails specific in Wisper, it is a Ruby library so works with all frameworks.

The only thing that might need changing are the examples in the README and Wiki. 

Would you be able to submit a Pull Request with the necessary changes?

**Comment by kirantpatil** [comment]
Thanks for clarification.
Let me start using it in our project and then I will plan for Pull Request.
