### ISSUE TITLE
Surprising results when leveraging ActiveModel::Dirty

### ISSUE THREAD

**Issue by cec** [krisleech/wisper#140]
Hi,

I have been using Wisper quite extensively in a Rails app at work and I really have to thank you for this gem, it's helping me a lot to keep my models clean.

Today, I noticed a unexpected behavior, at least unexpected to me, so I decided to open an issue to get some insight on this.

In my Communication model I have this callback

` after_save { |communication| broadcast(:communication_saved, communication) }`

and I setup a subscriber for this event as a global listener

`Wisper.subscribe(CommunicationSubscriber.new, scope: :Communication)`

In `CommunicationSubscriber` I need to check which attributes of the communication were changed.

Since the event is broadcast in an after_save, I use the following line

`changes = communication.previous_changes `

instead of 

`changes = communication.changes`

However, to my surprise, `previous_changes` returns a empty hash, while `changes` returns the actual changes.

According to the docs, `previous_changes` exists for the sole purpose of keeping track of changes on a AR object across a single save operation.

Are you aware of this peculiarity? 
If so, can you please explain to me why it happens?

**Comment by krisleech** [comment]
I do not think this will have anything to do with Wisper.

If you inspect `previous_changes` in an `after_save` hook do you still get an empty hash?

**Comment by cec** [comment]
Hi @krisleech!

You are right, indeed, in the hook `previous_changes` is empty. 
Then this is some inner details of how callbacks work in Rails.

I didn't check that cause to me it is an inconsistency with the API and docs.
I'll ask on the rails repo then.

Thank you for coming back to me so quickly!

Have a great day,
cec

**Comment by krisleech** [comment]
👍
