### ISSUE TITLE
Question: combining command objects

### ISSUE THREAD

**Issue by sineed** [krisleech/wisper#144]
Hi!

First of all thanks for this gem! Recently we started to use it in our team and find it very useful for domain separation.

I have a small question: have anybody faced with problem of combining service/command objects which use publish/subscribe pattern?

As an example I have two simple services:

```ruby
module Orders
  class Create
    include Wisper::Publisher

    attr_reader :params, :order

    def initialize(order = Order.new, params)
      @order = order
      @params = params
      subscribe(OrderListener, async: true)
    end
    
    def call
      order.assign_attributes(params)
      if order.valid?
        order.save
        broadcast :order_created, order
      else
        broadcast :order_creation_failed, order
      end
    end
  end

  class Publish
    include Wisper::Publisher

    attr_reader :order

    def initialize(order)
      @order = order
      subscribe(OrderListener, async: true)
      subscribe(PushNotificationListener, async: true)
    end
    
    def call
      if order.can_transition_to?(:published)
        order.publish
        broadcast :order_published, order
      else
        broadcast :order_publishing_failed, order
      end
    end
  end
end

```

The main idea is to have an ability to run these services in sequential order and atomically. So if **both** conditions are met then `order_created` and `order_published` are sent. But if **any** of conditions fails, then `order_creation_failed` and `order_publishing_failed` are sent. Also db-related stuff must be wrapped in transaction and rollbacked if, for example, we can not publish previously saved order.

Also I continue using these services separately.

As a WA I have `Orders::CreateAndPublish` class with similar but combined code that meets requirements above.

So maybe somebody faced with similar problem and can share with his/her experience?

**Comment by krisleech** [comment]
Questions should be on StackOverflow please.
