### ISSUE TITLE
Broadcast matcher needlessly duplicated from wisper-rspec library

### ISSUE THREAD

**Issue by ecbrodie** [krisleech/wisper#152]
@krisleech I am working on a project that uses the latest version of wisper (currently 1.6.1) and wisper-rspec (currently 0.0.2). The require "wisper/rspec/matchers" to require the BroadcastMatcher (as suggested by wisper-rspec's README" is ambiguous due to this matcher existing in both projects.

I think that this matcher should only exist in one project and not the other. I would personally vouch for this to only exist in wisper-rspec, due to that version's broadcast method accepting 1-to-many arguments similar to wisper's main broadcast argument whereas the wisper version only accepts one argument.

Cross-referenced to https://github.com/krisleech/wisper-rspec/issues/19, depending on which library will actually implement a fix.

**Comment by krisleech** [comment]
Wisper 1.x has the rspec matcher included, it is removed in the unreleased Wisper 2.x (master branch) and moved in to the wisper-rspec gem. Both versions 1.x and 2.x (master branch) have different README's.

You shouldn't use wisper-rspec with v1.x.

I think the solution is to release v2.x (#153) as the README seen when visiting the Wisper Github page will be correct.

**Comment by ecbrodie** [comment]
@krisleech that sounds awesome that an official release of v2 will be planned. Then we can close this issue once that is out.

**Comment by krisleech** [comment]
v2.0.0 has been released today :smile:

**Comment by ecbrodie** [comment]
Noice!
