### ISSUE TITLE
Specs for whisper events

### ISSUE THREAD

**Issue by rusikf** [krisleech/wisper#161]
How to test broadcasting events?
It looks, that with `whisper-rspec` there is no way to test like this:
```ruby
class Publish
  include Wisper::Publisher
  def initialize
  end
  def call
    broadcast(:awesome)
  end
end

expect_any_instance_of(Publish).to broacast(:awesome).once
```

**Comment by krisleech** [comment]
Have you tried the above, if so, I guess support for `expect_any_instance_of` would need adding to wisper-rspec. I would be happy to accept a Pull Request to add this if you can figure out how to add it.

**Comment by krisleech** [comment]
Please re-open if you need further help.
