### ISSUE TITLE
Delegate Wisper events to another publisher

### ISSUE THREAD

**Issue by hotavianom** [krisleech/wisper#167]
I would like to delegate my events to another instance. So I can delegate everything for a higher level instance to deal with those events.

Example:
```ruby
class ClassA
  include Wisper::Publisher

  def call
    publish(:class_a_called)
  end
end

class ClassAWrapper
  include Wisper::Publisher

  def call
    wrapped_class = ClassA.new
    wrapped_class.delegate_to(self) # this is the method I need
    wrapped_class.call
  end
end

wrapper = ClassAWrapper.new
wrapper.on(:class_a_called) do 
  puts "Catch it here"
end
wrapper.call
```

**Comment by krisleech** [comment]
```ruby
class ClassAWrapper
  include Wisper::Publisher

  def call
    wrapped_class = ClassA.new
    wrapped_class.subscribe(self, prefix: 'on')
    wrapped_class.call
  end
 
  def on_class_a_called(*args)
    broadcast(:class_a_called, *args)
  end
end

wrapper = ClassAWrapper.new

wrapper.on(:class_a_called) do 
  puts "Catch it here"
end

wrapper.call
```

**Comment by hotaviano** [comment]
Hi @krisleech, thank you for reply me.

I think you didn't get point I was trying to reach, that you showed is a great point too. Let me show you a more detailed example:

Bellow we have a class that update the coffee state
```ruby
class UpdateCoffeeState
  include Wisper::Publisher
  def initialize(state)
    @state = state
  end

  def call
    # do something cool here
    publish(:after_coffee_state_changed, @state)
  end
end
```

In the coffee maker I can get this event triggered before and pass through this new class.
```ruby
class CoffeeMaker
  include Wisper::Publisher
  def call
    service = UpdateCoffeeState.new('done')
    service.on(:after_coffee_state_changed) { |state| publish(:after_coffee_state_changed, state) }
    service.call
  end
end
```

Looking bellow my problem seems solved
```ruby
coffee_maker = CoffeeMaker.new
coffee_maker.on(:after_coffee_state_changed) do |state|
  puts "Coffee state changed to: #{state}"
end
```

but now, because I have another global listener getting all infos for log reasons, all times I use this structure I got two events, but I would like to have just one.
```ruby
Wisper.subscribe(LogEventsListener.new)
```

So, because of this I would like to delegate the event to another class, so I can keep just that event

```ruby
class CoffeeMaker
  include Wisper::Publisher
  def call
    service = UpdateCoffeeState.new('done')
    service.delegate_to(self)
    service.call
  end
end
```

I think this method `delegate_to` it's not a better name for that, but it means I'll publish all events of this service to another.

**Comment by krisleech** [comment]
Yes, you'll end up with two events, I hadn't considered that.

I can't, at the moment, think of a good way to implement `#delegate_to` without adding complexity to Wisper.

When an event is [broadcast](https://github.com/krisleech/wisper/blob/master/lib/wisper/publisher.rb#L43) it sends an instance of `self` (the publisher). Potentially we could, in [ObjectRegistration#broadcast](https://github.com/krisleech/wisper/blob/master/lib/wisper/registration/object.rb#L15), ask the publisher for the target for the events, by default it would return itself, but it could return some other object which is set using `#delegate_to`. But again this would add complexity to Wisper which I want to avoid.

The other option I can think of is to use a [custom broadcaster](https://github.com/krisleech/wisper/wiki/Write-custom-broadcasters) which would do something similar to the above. This is more likely a better option as the complexity can be contained in the broadcaster which could be in a separate gem.

**Comment by xiaohui-zhangxh** [comment]
I got the same case, when one publisher calls another publisher, write duplicate broadcast actions seem to be stupid, so I write this feature:

```ruby
class CoffeeMakerPublisher
  include Wisper::Publisher
  include Wisper::Bubbleable

  def power(on_or_off)
    state = CoffeeStatePublisher.new
    # ** bubble events here **
    state.bubble(:power_on, :power_off).to(self)
    state.on(:power_on) { broadcast(:warming) }
    state.change(on_or_off)
  end
end
```

see https://github.com/xiaohui-zhangxh/wisper-bubbleable
