### ISSUE TITLE
'console' and 'setup' executable names too general and conflict with other gems

### ISSUE THREAD

**Issue by keithrbennett** [krisleech/wisper#180]
I just installed the 'tty' gem. It is dependent on wisper, and I got this:

`wisper's executable "console" conflicts with envied`

I recommend removing these executables or renaming them to more specific names.

**Comment by keithrbennett** [comment]
It was pointed out to me that it would be just as effective to merely exclude them from the packaged gem (the `spec.files` line in the .gemspec file).

**Comment by krisleech** [comment]
`bin/console` is used by many gems as it is part of the default template used by `bundler gem`.

But they could be excluded from the packaged gem.
