### ISSUE TITLE
Should we choose WisperNext over Wisper?

### ISSUE THREAD

**Issue by gnumarcelo** [krisleech/wisper#187]
Hi,
we are planning to add Wisper to our project (a Rails 5.2, not greenfield app) but reading the README it mentions that *For greenfield applications you might also be interested in WisperNext and Ma.* but it is not clear why we should do it. Is Wisper gem planning to not do releases anymore or is it related to something else?

Thank you!

**Comment by krisleech** [comment]
WisperNext is a rewrite of Wisper, it isn't backwards compatible. I haven't used in production.
It also needs async adapters writitng, which is a great opportunity for anyone who wants to do some open source.
So if you want to invest a bit of time it might be worth it.
