### ISSUE TITLE
Using Fibers breaks the execution of Wisper

### ISSUE THREAD

**Issue by rlopzc** [krisleech/wisper#189]
Hello! I opened [this](https://github.com/rmosolgo/graphql-ruby/issues/3430) issue and I couldn't get it working with the proposed solution.

Seems that here: https://github.com/krisleech/wisper/blob/7cff5bca86cf0afa14cde20832bf4f0de6a52188/lib/wisper/temporary_listeners.rb#L27-L29 it needs to get updated to work with Fibers.

I don't have experience with Fibers but I'll take a look and if I get it working I'll open a PR

Or do you think the solution could be something different?

**Comment by krisleech** [comment]
It would be great if someone could look in to a PR for this. I also not familiar with the problems with `Thread.current` and fibers.
