### ISSUE TITLE
Ruby 3.0 support for broadcast with kwargs

### ISSUE THREAD

**Issue by dvandersluis** [krisleech/wisper#190]
When broadcasting with kwargs, an `ArgumentError` is raised in Ruby 3.0:

```ruby
broadcast(:user_changed, initial_id: user_id_before_last_save, final_id: user_id)
```

```ruby
ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: initial_id, final_id)
```

This worked fine on Ruby 2.6, but because `Publisher#broadcast` doesn't handle kwargs, it breaks in 3.0.

**Comment by dvandersluis** [comment]
If anyone else is encountering this, I fixed it by monkey patching `wisper` on my codebase:

```ruby
module Wipser
  module Publisher
    # Wisper 2.0.1 does not properly support Ruby 3 kwargs
    def broadcast(event, ...)
      registrations.each do |registration|
        registration.broadcast(clean_event(event), self, ...)
      end
      
      self
    end
  end
end
```

I'd create a PR but `...` won't work for lesser ruby version so I'm not exactly sure what to do.

**Comment by doits** [comment]
I opened #192 to hopefully make it compatible with ruby 3, needs some more testing though to make sure it really works like intended!

**Comment by krisleech** [comment]
I'd love to get Ruby 3.0 support in Wisper. But it would need to be backwards compatible. Otherwise we would need to release a new major version dropping Ruby 2.x support and maintain both major versions until Ruby 2.x is EOL, which will be a long time.

**Comment by doits** [comment]
#192 is compatible with `>= 2.7`, so for all officially supported ruby versions but `2.6`. For `2.6` the [ruby team writes](https://www.ruby-lang.org/en/downloads/): `In security maintenance phase (will EOL soon!)`. 

The only solution I see to make it compatible with `2.6` *and* `3` is to use [ruby2_keywords](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation). I am not sure if supporting `2.6` is worth the hassle (EOL soon). What do you think?

**Comment by krisleech** [comment]
We can do a major version release which drops support for 2.6, we need to document it in the CHANGELOG, that it is a breaking change.

**Comment by krisleech** [comment]
If anyone wants to pick this up it would be great. We can drop support for EOL Rubies and add Ruby 3 keyword arguments support.

**Comment by merrington** [comment]
@krisleech - I opened #197 to address this, hopefully. Wondering if you could take a look when you get a chance, thanks!

**Comment by benlieb** [comment]
I think someone should just publish a clone of this that is ruby 3 ready. The wisper-next gem isn't as full-featured yet as this, and the async functionality for that doesn't seem to be ready either. Frustrating.

**Comment by benlieb** [comment]
@krisleech I regret coming off as an entitled whiner. It makes sense that that would be triggering for you, especially as the author. No real excuses, I just remember being short on time and short on options for what I needed that week. 

I appreciate your work!

**Comment by patrickemuller** [comment]
Any news on this?

**Comment by krisleech** [comment]
Just waiting on https://github.com/krisleech/wisper/pull/197

**Comment by krisleech** [comment]
Anyone on this thread please try https://github.com/krisleech/wisper/pull/205 on your codebase and report back any issues... We are close to a release if we can get this tested on some production codebases.
