### ISSUE TITLE
Request to Contribute Documentation Updates

### ISSUE THREAD

**Issue by offjeff91** [krisleech/wisper#209]
Hello,

I hope this message finds you well. I have been actively using your library in a recent project and have found it to be incredibly valuable. I noticed that the documentation might benefit from some updates to reflect recent changes and improvements.

I wanted to reach out and ask whether you are currently open to receiving pull requests for documentation updates. I would be more than happy to contribute to enhancing the documentation to make it even more accessible and useful to the community.

Please let me know your thoughts on this, and if you are indeed open to such contributions, I would be excited to work on a pull request to help improve the documentation.

Thank you for your time and consideration.

Best regards,

Jefferson Fernandes.

**Comment by krisleech** [comment]
Yes, open to PR's for the docs, there is also the wiki too.
