### ISSUE TITLE
An easy way of disabling wisper within a block

### ISSUE THREAD

**Issue by fabriciofreitag** [krisleech/wisper#211]
I'm using Wisper to replace model callbacks, so by doing this:
```
module CommitBroadcastable
  extend ActiveSupport::Concern
  include Wisper::Publisher

  included do
    after_commit :broadcast_after_commit
  end

  private

  def broadcast_after_commit
    broadcast("#{self.class.name.demodulize.underscore}_after_commit", self)
  end
end
```

I can create/subscribe multiple listeners that would be triggered by the same model:

```
class FooListener 
  def foo_after_commit(foo) # assuming there's a models/foo.rb
    foo.do_stuff!
  end
end

class AnotherFooListener 
  def foo_after_commit(foo) # assuming there's a models/foo.rb
        foo.do_other_stuff!
  end
end
```

That is great, but I came across a problem:
If `FooListener` calls methods (outside my control, like another 3rd party gem that changes that model) that would also trigger `AnotherFooListener`, I end up loosing the right state of `foo.previous_changes`.

So then finally my question, is there a proper was of doing?:
```
class FooListener 
  def foo_after_commit(foo) # assuming there's a models/foo.rb
    Wisper.do_not_publish_anything_please { foo.do_stuff! } 
  end
end
```

**Comment by krisleech** [comment]
would it be possible to store all subscribed listeners, unsubscribe them and then resubscribe them? Other than you could pass an id instead of the model itself and re-fetch the model, or pass the previous changes as part of the payload.
