### ISSUE TITLE
console" from wisper conflicts with installed executable from fastlane

### ISSUE THREAD

**Issue by harsjadh** [krisleech/wisper#213]
Hi,

While installing the gem install gazer getting below error
ERROR:  Error installing gazer:
	"console" from wisper conflicts with installed executable from fastlane
Successfully installed tty-tree-0.4.0
Successfully installed unicode_utils-1.4.0
Successfully installed strings-ansi-0.2.0
Successfully installed strings-0.2.1
Successfully installed tty-color-0.6.0
Successfully installed pastel-0.[8](https://github.com/uniphore/looker-integration/actions/runs/8700695647/job/23862649558#step:8:9).0
Successfully installed tty-table-0.12.0
Error: Process completed with exit code 1.

**Comment by harsjadh** [comment]
Hi,

Gentle Remainder !!!

Any update on above issue as still facing the issue.

**Comment by krisleech** [comment]
hey, what's the fix for this? I guess to exclude anything in bin from the gem?
