### ISSUE TITLE
on(...) Callbacks doesn't seem to work correctly inside Grape API

### ISSUE THREAD

**Issue by danielkummer** [krisleech/wisper#58]
Hello, 
I've tried using the listeners as desribed in the howto inside a Grape API with success and fail callbacks. 

The basic code is as follows:

```
post do
  service = RatingService.new
  service.execute(rating)
  service.on(:rating_successful) do |rating|
    status(200)
    {
        message: "Successfully rated #{rating.topic.name}"
    }
  end
  service.on(:rating_failed) do |errors|
   render_api_error!(errors, 400)
  end
end
```

Now when I post to this Grape API I don't get the expected response defined in the on() blocks but instead a direct response object from the Whisper Service:

```
{
    async: false,
    local_registrations: [
    {
        listener: { },
        on: [
            "all"
        ],
        with: null,
        prefix: "",
        allowed_classes: [ ]
    },
    {
        listener: { },
        on: [
            "all"
        ],
        with: null,
        prefix: "",
        allowed_classes: [ ]
    },
    {
        listener: { },
        on: [
            "rating_successful"
        ]
    },
    {
        listener: { },
        on: [
        "rating_failed"
        ]
    }
    ]
}
```

I tried moving the execute() call AFTER the on() blocks but it didn't work either...

Am I missing something?
Any help would be greatly appreciated!

**Comment by Dan2552** [comment]
Just came across this. Just posting this as a warning incase anybody comes here straight from Google. 

I can confirm `body` works and is safer to use as the readme for this repo says:

> Do not return from inside a subscribed block, due to the way Ruby treats blocks this will prevent any subsequent listeners having their events delivered.
