### ISSUE TITLE
Broadcasting to protected methods

### ISSUE THREAD

**Issue by midas** [krisleech/wisper#75]
First thanks for the hard work you have put in on Wisper.  I love this library and use it in every Ruby project I participate in.

I am not sure how you will feel about this issue, but I do not particularly like that the message handlers must be public methods as it mucks up the public API of the class.  Have you considered when determining if a listener will receive a broadcasted message with `respond_to?( :some_message, true )`?

If you wanted to get a little more restrictive you could only allow for public or protected methods and not use #respond_to?, but instead a custom method that looks at only public and protected methods.

C# handles this by exposing a public delegate and a protected handler method.  This allows for a clear public API of the class.

Thanks!

**Comment by krisleech** [comment]
This could potentially be solved by having Wisper call an `on_event` method (if it exists) instead of a method named after the event. The `on_event` method in the controller can then call a private method named after the event.

**Comment by krisleech** [comment]
Closing for now, this will be possible in Wisper 2.
