### ISSUE TITLE
`respond_to` name collision

### ISSUE THREAD

**Issue by SebastianOsuna** [krisleech/wisper#91]
Hello,

I was trying out Wisper, creating a global listener and using a scaffolded ActionController as a publisher. After the action was finished, the controller was supposed to broadcast a different message whether a `save` was successful or not. But I got this exception:

`must give at least one event` 

Here is my code

``` ruby
 respond_to do |format|  # Exception marked here
      if @my_model.save
        broadcast(:create_model_success, @my_model)
        format.html { redirect_to @my_model, notice: 'My model was successfully created.' }
        format.json { render :show, status: :created, location: @my_model }
      else
        broadcast(:create_model_error, @my_model)
        format.html { render :new }
        format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    end
```

I then noticed the publisher module has a `respond_to` method. So my guess is a name collision. Here is my working code: 

``` ruby
# respond_to do |format|
      if @my_model.save
        broadcast(:create_model_success, @my_model)
        redirect_to @my_model, notice: 'My model was successfully created.'
        # format.html { redirect_to @my_model, notice: 'My model was successfully created.' }
        # format.json { render :show, status: :created, location: @my_model }
      else
        broadcast(:create_model_error, @my_model)
        render :new
        # format.html { render :new }
        # format.json { render json: @my_model.errors, status: :unprocessable_entity }
      end
    # end
```

You can check my complete project here: https://github.com/SebastianOsuna/wisper_mailing

**Comment by tute** [comment]
I use `respond_to do |format|` to display different views for different formats. Is there a workaround for this? Thank you!

**Comment by krisleech** [comment]
There is a release candidate you can use:

```ruby
gem 'wisper', '2.0.0.rc1'
```

If you are using the latest 1.x Wisper release and get no deprecation warning you should be good :)

Out of interest why do you broadcast events from the web layer (controller) instead of the domain layer (model, service etc.)?

**Comment by tute** [comment]
Thanks for your quick reply! I ended up encapsulating the broadcast in an inline class.

I didn't pick 2.0.0.rc1 because it was released as candidate almost a year ago now; without a real major release I thought it would be less up to date than the ~1.6 tree.

The reason I have the calls in the controller is that this is an endpoint used to perform some authorization and download a static file. There is no domain model I can think of to encapsulate this behavior.

Thank you for your gem and input! It is very much appreciated. :)

**Comment by krisleech** [comment]
I think an inline class is a good idea given your use case.

2.0.0.rc1 is backwards compatible with 1.6, 2.0 is mostly a refactor (rewrite). The feature set and API is the same (apart from some deprecated method, hence the change to 2.0).

No problem :)
