### ISSUE TITLE
A copy of <SomeListenerHere> has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by mbajur** [krisleech/wisper#96]
Hello!
I'm trying to use global listeners in my rails app. According to wisper docs, i should put the following code in my initializer:

    Wisper.subscribe(OutstandingWorkValueListener.new)
    Wisper.subscribe(JobVideoCreatorListener.new)
    Wisper.subscribe(JobRatingsListener.new)

However, for some reason, from time to time (it's completely unpredictible! sometimes restarting a server does the job, sometimes not) i'm getting an error that says for exmaple:

    A copy of OutstandingWorkValueListener has been removed from the module tree but is still active!

Am i doing something wrong? What does that error mean? Thanks in advance for any clues.

**Comment by krisleech** [comment]
This has been [reported before](https://github.com/krisleech/wisper/issues/44) and I think it is related to Rails class reloading.

You could try and prevent Rails reloading the listener. Please let me know if you have any success...

**Comment by mbajur** [comment]
Thanks for your quick reply @krisleech !

To be hones, i do not feel quite confident with all these things that are going on in here. I've read the thread and related PRs but i still have no idea how to deal with that. Can you give me some advice on that?

**Comment by krisleech** [comment]
I have not had this problem so I don't have any advice. Sorry. You could try posting a question on StackOverflow maybe... /cc @gersmann @mzubala

**Comment by mbajur** [comment]
Ok, i see, no problem.
I have managed to temporarily deal with that issue with the following code:

    class RailsWisper

      def self.subscribe(obj)
        unless listeners.include? obj.class.name
          Wisper.subscribe(obj)
        end
      end

      private

      def self.listeners
        Wisper::GlobalListeners.listeners.map { |l| l.class.name.to_s }
      end
    end

    # Global wisper listeners
    RailsWisper.subscribe(OutstandingWorkValueListener.new)
    RailsWisper.subscribe(JobVideoCreatorListener.new)
    RailsWisper.subscribe(JobRatingsListener.new)
    RailsWisper.subscribe(SuccessRateListener.new)
    RailsWisper.subscribe(LogListener.new)

But i'm not able to test if the issue is now gone for good (it's a completely random thing!). If anyone has any better and bullet-proof solution, please share it :)

**Comment by gersmann** [comment]
@mbajur don't know about better, but I have a branch with a solution which has been rock solid in production for months now. See https://github.com/gersmann/wisper. There is also a PR on that referenced above, basically all you need to do is to just subscribe by passing the class reference instead of an instance reference.

**Comment by mbajur** [comment]
@gersmann we're talking about a `master` branch, right?

**Comment by gersmann** [comment]
@mbajur don't understand the question, sorry. please have a look here: https://github.com/krisleech/wisper/pull/46

**Comment by krisleech** [comment]
@mbajur He is talking about the master branch on his clone of Wisper. In Gemfile add `gem 'wisper', github: 'gersmann/wisper'` and then subscribe a class, not object.

However I would stick with your version for now because if it does work it can be added to the Wiki or even as a separate gem such as `wisper-rails`. If you do, please report back.

**Comment by mbajur** [comment]
Oh, sorry, i've misunderstood your comment @gersmann 

Sure, no problem @krisleech , i'll create a simple gem for that and post a link in here in a moment

**Comment by mbajur** [comment]
Ok, after playing with my fix for a while, it turns out that it's not fixing the problem. However, @gersmann 's fork seems to be working great

**Comment by krisleech** [comment]
Please feel free to re-open this issue in the future.
